# Path: config.yml
# This is the configuration file for the project.
# It is used to store the password and other sensitive information.
# It is not tracked by git, so you can safely edit it.

# The following is the database information.
host: localhost
user: root
passwd: 
db: ComNet
table: WIFI

# The following is your server IP, server port and the MAC of your mobile phone to be localized.
server_ip: 
server_port: 
mobile_mac: 

# The following is the mMACs of the 3 WIFI detector.
mmacs: 
  - 14:6b:9c:f4:04:3a
  - 14:6b:9c:f4:04:3b
  - 14:6b:9c:f4:04:0b

# The following is the coordinates of the 3 WIFI detector (corresponding to the mMACs above)
coordinates: 
  - [2.7, 0]
  - [1.9, 3.2]
  - [0.3, 1.8]

# The following is the room size in xy (in meters). e.g [10, 10]
room_size: [3.5, 4.0]

# The following is the size and location of obstacles in xy (in meters). e.g [1, 2, 3, 4] means [1, 2] * [3, 4]
obstacle: [
  [2.1, 3.4, 0.3, 1.2],
  [0.1, 1.5, 1.25, 1.85],
  [0.1, 1.5, 2.6, 3.2],
  [1.8, 3.2, 1.25, 1.85],
  [1.8, 3.2, 2.6, 3.2]
]

# The following is the ground truth trajectory of the mobile phone in xy (in meters). e.g. [1, 2], [3, 4] means [1, 2] -> [3, 4]
ground_truth_trajectory: [
  [0.3, 0.3],
  [0.3, 1.2],
  [1.6, 1.2],
  [1.6, 2.0],
  [0.5, 2.0],
  [0.5, 2.5],
  [1.6, 2.5],
  [1.7, 3.3],
  [2.5, 3.3]
]